apiVersion: v1
kind: Pod
metadata:
  name: madvisor-demo
  labels:
    app: madvisor-demo
spec:
  containers:
    - name: dummy-app
      image: daxroc/madvisor-dummy:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: metrics
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 2
        periodSeconds: 5

    - name: madvisor
      image: daxroc/madvisor:latest
      imagePullPolicy: IfNotPresent
      stdin: true
      tty: true
      env:
        - name: METRIC_TARGETS
          value: "localhost:8080"
        - name: TERM
          value: "xterm-256color"
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
